version: '3.8'
services:

  newton_raphson:
    build: ./Newton_Raphson
    ports:
      - "5000:5000"

  secante:
    build: ./secante
    ports:
      - "5002:5002"

  biseccion:
    build: ./biseccion
    ports:
      - "5001:5001"
      
  punto_fijo:
    build: ./punto_fijo
    ports:
      - "5003:5003"

  broyden:
    build: ./broyden
    ports:
      - "5004:5004"

  trapecio:
    build: ./Trapecio
    ports:
      - "5006:5006"
